language: python
python:
  - 2.6
before_install:
  - sudo apt-get install libpcre3-dev
install:
  - make bin/pybot
  - make var/supervisord.pid
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: 
  - make robot

