---
language: python
python: '2.7'
install:
- curl -O http://saucelabs.com/downloads/Sauce-Connect-latest.zip
- unzip Sauce-Connect-latest.zip
- java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_ID
  -f CONNECTED 1>/dev/null &
- JAVA_PID=$!
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- bash -c "while [ ! -f CONNECTED ]; do sleep 2; done"
script: bin/test
after_script:
- kill $JAVA_PID
env:
  global:
  - secure: ! 'UDDQpOnB2b3/eLZ91eZICI0ONe3Z2JFl9PcK4X+32vq3QwUAZnASe9+u4xph
      yUNLrHPBly52e8rDChcr9qYga7dt4l4rBD0FBHDXYB54ZfLbryGjyzylzIZ+
      KDclDYy8v6S1dhP5RSkrhq0td9JtZQZxdnA7hzZ6BIKfA5bJFeQ='
  - secure: ! 'fXGxapnlXsaom0+F6gxVXY3QcEOjKqz8UukDDFlM7BzgWITmzVylwbARaev0
      ueMFNtZSZOXP57NqvN27TL7fuZnd5D6x37LxIGEHbvtauVIK4o4B+p5Ug42x
      YGULDySxeI/5dxnji2zgEO3yBG/Q7kEIJ6RhaSLA01u2XwqYRds='
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
  matrix:
  - ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
  - ROBOT_BROWSER=chrome ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
  - ROBOT_BROWSER=ie ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
