---
language: python
python: '2.7'
addons:
  sauce_connect:
  - username: $SAUCE_USERNAME
  - access_key: $SAUCE_ACCESS_KEY
install:
- virtualenv buildout --no-setuptools
- mkdir -p buildout-cache/downloads
- buildout/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
script: bin/test
env:
  global:
  - secure: ! 'YLol0TyHB+XAUbCzzjfc5JJ5AFqEi/GVhGphtAAcSv8+JY6MhTVVTjyCPeoK
      2nT7tDhQRnYKOAMBmTuP/TUdzFqBf5LvjrFxvcjBawJMRW85kuYEuXsS8XEx
      C+lc1bbXSUPGA0x03tvSHIYbCowvVPZNUupxgRQdW2QLa5HcSuQ='
  - secure: ! 'YhG9gTzNMbQWiHLO6RU2J9btjB8L4X/QpKgu4c48XHYEf0Mwgxi5kKhZTTqp
      KY6/buwYhcBFWh0PQVC1b35lHHxI+bD4/d3v8xea7v670COdP0zMrgjXlSLn
      bfV7g3/doSmAUtbEyUQdfzmWS8kyst0div6XzpWtR3cl6lP6Tfo='
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
  matrix:
  - ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
  - ROBOT_BROWSER=ie ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
